name: "Build Docker"
on:
  push:
    branches: ["matan/train-figgs"]
permissions:
  id-token: write
  contents: read
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
jobs:
  build-llama-factory:
    name: "Build llama-factory"
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::493158179392:role/github-DecartAI
          aws-region: us-east-1
      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: "public.ecr.aws/v5m9k7e6/llama-factory:${{ github.sha }}"
          cache-from: type=s3,region=us-east-1,bucket=figgs-build-cache,name=llama-factory
          cache-to: type=s3,region=us-east-1,bucket=figgs-build-cache,name=llama-factory
    outputs:
      image: "public.ecr.aws/v5m9k7e6/llama-factory:${{ github.sha }}"
